// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7y5RW_-oHpVZsJJiJ-Ba6XrstYRWR2aQ',
    appId: '1:359661763058:web:7095d37abb4cd293f8936b',
    messagingSenderId: '359661763058',
    projectId: 'guide-me-20196',
    authDomain: 'guide-me-20196.firebaseapp.com',
    storageBucket: 'guide-me-20196.appspot.com',
    measurementId: 'G-0RFP9WNQ1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqOIC-8_Yf3tRlswzTPzgwOn9BSjZxvLI',
    appId: '1:359661763058:android:1d5dc938ba0425e3f8936b',
    messagingSenderId: '359661763058',
    projectId: 'guide-me-20196',
    storageBucket: 'guide-me-20196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0pQwaBhcao8_AZDZKO9ZHA2pKsuUEtlo',
    appId: '1:359661763058:ios:931e178a7f237837f8936b',
    messagingSenderId: '359661763058',
    projectId: 'guide-me-20196',
    storageBucket: 'guide-me-20196.appspot.com',
    iosClientId:
        '359661763058-j6k23c4ul1n5hd55ei78b5rmab4psv11.apps.googleusercontent.com',
    iosBundleId: 'com.Guide-me.app',
  );
}
